task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from tasks import views as tasks_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', tasks_views.home, name='home'),
    path('tasks/prioritized/', tasks_views.prioritized_tasks, name='prioritized_tasks'),
    path('task-list/<int:pk>/', tasks_views.task_list_detail, name='task_list_detail'),
    path('task-list/<int:pk>/delete/', tasks_views.delete_task_list, name='delete_task_list'),
    path('task-list/create/', tasks_views.create_task_list, name='create_task_list'),
    path('task-list/<int:pk>/update/', tasks_views.update_task_list, name='update_task_list'),
    path('task-list/<int:task_list_pk>/task/create/', tasks_views.create_task, name='create_task'),
    path('task-list/<int:task_list_pk>/task/<int:task_pk>/update/', tasks_views.update_task, name='update_task'),
    path('task/<int:pk>/toggle/', tasks_views.toggle_task, name='toggle_task'),
    path('task/<int:pk>/delete/', tasks_views.delete_task, name='delete_task'),

    path('register/', accounts_views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
]

handler404 = 'accounts.views.custom_page_not_found_view'

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class TaskList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, null=False, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, null=False, blank=False)
    name = models.CharField(max_length=128, null=False, blank=False)
    due_date = models.DateTimeField(null=True, blank=True)
    is_important = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def is_expired(self):
        return not self.is_completed and self.due_date > timezone.now()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>FocusBrew</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'header.html' %}
  <!-- End Header -->

  <!-- ======= Sidebar ======= -->
  {% include 'sidebar.html' %}
  <!-- End Sidebar-->

  <main id="main" class="main">
    {% block content %}{% endblock %}
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>FocusBrew</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      Designed by Sirin Gulec, Dina Dienta
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css" integrity="sha512-YdYyWQf8AS4WSB0WWdc3FbQ3Ypdm0QCWD2k4hgfqbQbRCJBEgX0iAegkl2S1Evma5ImaVXLBeUkIlP6hQ1eYKQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js" integrity="sha512-RCgrAvvoLpP7KVgTkTctrUdv7C6t7Un3p1iaoPr1++3pybCyCsCZZN7QEHMZTcJTmcJ7jzexTO+eFpHk4OCFAg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#id_due_date').datepicker();
    });
  </script>
</body>

</html>

templates/header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'home' %}" class="logo d-flex align-items-center">
      <img src="assets/img/logo.png" alt="">
      <span class="d-none d-lg-block">FocusBrew</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div><!-- End Logo -->
  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'img/blank-profile-img.png' %}" alt="Profile" class="rounded-circle">
          <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.first_name }} {{ user.last_name }}</span>
        </a><!-- End Profile Image Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{ user.first_name }} {{ user.last_name }}</h6>
            <span>{{ user.email }}</span>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
              <i class="bi bi-box-arrow-right"></i>
              <span>Logout</span>
            </a>
          </li>

        </ul><!-- End Profile Dropdown Items -->
      </li><!-- End Profile Nav -->

    </ul>
  </nav><!-- End Icons Navigation -->
</header>

templates/sidebar.html
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link collapsed{% if request.resolver_match.url_name == 'home' %}x{% endif %}" href="{% url 'home' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li><!-- End Dashboard Nav -->

    <li class="nav-item">
      <a class="nav-link collapsed{% if request.resolver_match.url_name == 'prioritized_tasks' %}x{% endif %}" href="{% url 'prioritized_tasks' %}">
        <i class="bi bi-star"></i>
        <span>Prioritized</span>
      </a>
    </li>
    {% for task_list in task_lists %}
    <li class="nav-item">
      <a class="nav-link collapsed{% if request.resolver_match.kwargs.pk == task_list.pk and request.resolver_match.url_name == 'task_list_detail' %}x{% endif %}" href="{% url 'task_list_detail' task_list.pk  %}">
        <i class="bi bi-list-task"></i>
        <span>{{ task_list.name }}</span>
      </a>
    </li>
    {% endfor %}

  </ul>
  <div class="d-grid gap-2 mt-3">
    <a href="{% url 'create_task_list' %}" type="button" class="btn btn-primary pl-5 pr-5"><i class="bi bi-plus-square me-1"></i> Create Task List</a>
  </div>
</aside>